import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

import manifest from "./manifest.json" with { type: "json" };

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
let outdir = "./";
if (!prod) {
  const vault = process.env.OBSIDIAN_VAULT_PATH;
  if (!vault) {
    console.error("OBSIDIAN_VAULT_PATH is not set.");
    console.error("Copy .env.example to .env and set it to your vault path.");
    process.exit(1);
  }
  outdir = `${vault.replace(/\/$/, "")}/.obsidian/plugins/${manifest.id}`;
}

console.info(`\nSaving plugin to ${outdir}\n`);

esbuild
  .build({
    banner: {
      js: banner,
    },
    minify: prod ? true : false,
    entryPoints: ["src/main.ts", "src/styles.css"],
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "codemirror",
      "@codemirror/closebrackets",
      "@codemirror/commands",
      "@codemirror/fold",
      "@codemirror/gutter",
      "@codemirror/history",
      "@codemirror/language",
      "@codemirror/rangeset",
      "@codemirror/rectangular-selection",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/stream-parser",
      "@codemirror/text",
      "@codemirror/view",
      ...builtinModules,
    ],
    format: "cjs",
    watch: !prod,
    target: "es2020",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outdir: outdir,
  })
  .catch(() => process.exit(1));
